gay
codingidiots/react-starter-kit pull request #3
Opened 2019-01-06 11:19 UTC by FactAttacker

geoseong gay

2019-01-06 11:21 UTC, FactAttacker commented on .gitignore
> +#태성씨 게이
true

2019-01-06 11:23 UTC, geoseong commented on .gitignore
> +#태성씨 게이
@FactAttacker i'm not gay

2019-01-06 11:24 UTC, geoseong commented on .gitignore
> +#태성씨 게이
fix this right now

2019-01-16 06:56 UTC, geoseong requested changes
취소하슈

2019-01-16 07:01 UTC, FactAttacker reviewed
Test

2019-01-20 05:47 UTC, closed without merging